name: Deploy to Amazon EC2

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: executing remote ssh commands using password
      run: |
        echo "${{ secrets.EC2_TRAIN_SERVER_PEM }}" > train_server.pem
        echo "${{ secrets.EC2_PREDICT_SERVER_PEM }}" > predict_server.pem
        chmod 400 train_server.pem
        chmod 400 predict_server.pem
        mkdir -p ~/.ssh/ && touch ~/.ssh/known_hosts
        ssh-keyscan ec2-51-20-93-60.eu-north-1.compute.amazonaws.com >> ~/.ssh/known_hosts
        ssh-keyscan ec2-51-20-248-99.eu-north-1.compute.amazonaws.com >> ~/.ssh/known_hosts
        eval $(ssh-agent)
        ssh-add - <<< "${{ secrets.EC2_TRAIN_SERVER_PEM }}"
        ssh-add - <<< "${{ secrets.EC2_PREDICT_SERVER_PEM }}"
        ssh -T -i "train_server.pem" ubuntu@ec2-51-20-248-99.eu-north-1.compute.amazonaws.com 'bash -s' < ./deploy/script-train-server.sh
        ssh -T -i "predict_server.pem" ubuntu@ec2-51-20-93-60.eu-north-1.compute.amazonaws.com 'bash -s' < ./deploy/script-predict-server.sh
