name: Deploy to Amazon EC2

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: executing remote ssh commands using password
      run: |
        echo "${{ secrets.EC2_TRAIN_SERVER_PEM }}" | tr -d '\r' > train_server.pem
        chmod 400 train_server.pem
        ssh -T -i "train_server.pem" ubuntu@ec2-16-171-224-228.eu-north-1.compute.amazonaws.com 'bash -s' < ./deploy/script.sh
