# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        flake8 . --count
    - name: Test with pytest
      run: |
        pytest
    - name: Test CML
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Can use the default token for most functions
      run: |
        python ./cml/test.py
  
        echo "## Model metrics" >> report.md
        cat ./cml/metrics.txt >> report.md
        echo '![](./cml/metrics.jpg)' >> report.md
        cml comment create --publish report.md
