# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions: write-all
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    - name: Set up Node 16
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        flake8 . --count
    - name: Test with pytest
      run: |
        pytest
    - uses: iterative/setup-cml@v1
    - name: Test CML
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Can use the default token for most functions
      run: |
        python cml/test.py
  
        echo "## Model metrics" >> report.md
        cat cml/metrics.txt >> report.md
        echo '![](./cml/metrics.jpg)' >> report.md
        cml comment create --publish report.md
